# Generated by Django 4.0 on 2021-12-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
